using System;

namespace MetaphysicsIndustries.Giza
{
    public class JsonGrammar : Grammar
    {
        public Definition def_json = new Definition("json");
        public Definition def_object = new Definition("object");
        public Definition def_member = new Definition("member");
        public Definition def_value = new Definition("value");
        public Definition def_number = new Definition("number");
        public Definition def_string = new Definition("string");
        public Definition def_char = new Definition("char");
        public Definition def_unescaped = new Definition("unescaped");
        public Definition def_array = new Definition("array");

        public DefRefNode node_json_0_value;
        public CharNode node_object_0__007B_;
        public DefRefNode node_object_1_members;
        public CharNode node_object_2__002C_;
        public DefRefNode node_object_3_members;
        public CharNode node_object_4__007D_;
        public DefRefNode node_member_0_key;
        public CharNode node_member_1__003A_;
        public DefRefNode node_member_2_value;
        public CharNode node_value_0_false;
        public CharNode node_value_1_false;
        public CharNode node_value_2_false;
        public CharNode node_value_3_false;
        public CharNode node_value_4_false;
        public CharNode node_value_5_null;
        public CharNode node_value_6_null;
        public CharNode node_value_7_null;
        public CharNode node_value_8_null;
        public CharNode node_value_9_true;
        public CharNode node_value_10_true;
        public CharNode node_value_11_true;
        public CharNode node_value_12_true;
        public DefRefNode node_value_13_object;
        public DefRefNode node_value_14_array;
        public DefRefNode node_value_15_number;
        public DefRefNode node_value_16_string;
        public CharNode node_number_0__002D_;
        public CharNode node_number_1_0;
        public CharNode node_number_2_123456789;
        public CharNode node_number_3__005C_d;
        public CharNode node_number_4__002E_;
        public CharNode node_number_5__005C_d;
        public CharNode node_number_6_Ee;
        public CharNode node_number_7__002B__002D_;
        public CharNode node_number_8__005C_d;
        public CharNode node_string_0__0022_;
        public DefRefNode node_string_1_char;
        public CharNode node_string_2__0022_;
        public DefRefNode node_char_0_unescaped;
        public CharNode node_char_1__005C_;
        public CharNode node_char_2__0022__002F__005C__005C_bfnrt;
        public CharNode node_char_3_u;
        public CharNode node_char_4__005C_dabcdef;
        public CharNode node_char_5__005C_dabcdef;
        public CharNode node_char_6__005C_dabcdef;
        public CharNode node_char_7__005C_dabcdef;
        public CharNode node_unescaped_0__005C_l_005C_d_0020__0021__0023__0024__0025__0026__0027__0028__0029__002A__002B__002C__002D__002E__002F__003A__003B__003C__003D__003E__003F__0040__005C__005B__005C__005D__005E__005F__0060__007B__007C__007D__007E_;
        public CharNode node_array_0__005B_;
        public DefRefNode node_array_1_value;
        public CharNode node_array_2__002C_;
        public DefRefNode node_array_3_value;
        public CharNode node_array_4__005D_;

        public JsonGrammar()
        {
            Definitions.Add(def_json);
            Definitions.Add(def_object);
            Definitions.Add(def_member);
            Definitions.Add(def_value);
            Definitions.Add(def_number);
            Definitions.Add(def_string);
            Definitions.Add(def_char);
            Definitions.Add(def_unescaped);
            Definitions.Add(def_array);

            node_json_0_value = new DefRefNode(def_value, "value");
            def_json.Nodes.Add(node_json_0_value);
            def_json.StartNodes.Add(node_json_0_value);
            def_json.EndNodes.Add(node_json_0_value);

            node_object_0__007B_ = new CharNode(CharClass.FromUndelimitedCharClassText("{"), "{");
            node_object_1_members = new DefRefNode(def_member, "members");
            node_object_2__002C_ = new CharNode(CharClass.FromUndelimitedCharClassText(","), ",");
            node_object_3_members = new DefRefNode(def_member, "members");
            node_object_4__007D_ = new CharNode(CharClass.FromUndelimitedCharClassText("}"), "}");
            def_object.Nodes.Add(node_object_0__007B_);
            def_object.Nodes.Add(node_object_1_members);
            def_object.Nodes.Add(node_object_2__002C_);
            def_object.Nodes.Add(node_object_3_members);
            def_object.Nodes.Add(node_object_4__007D_);
            def_object.StartNodes.Add(node_object_0__007B_);
            def_object.EndNodes.Add(node_object_4__007D_);
            node_object_0__007B_.NextNodes.Add(node_object_1_members);
            node_object_0__007B_.NextNodes.Add(node_object_4__007D_);
            node_object_1_members.NextNodes.Add(node_object_2__002C_);
            node_object_1_members.NextNodes.Add(node_object_4__007D_);
            node_object_2__002C_.NextNodes.Add(node_object_3_members);
            node_object_3_members.NextNodes.Add(node_object_2__002C_);
            node_object_3_members.NextNodes.Add(node_object_4__007D_);

            node_member_0_key = new DefRefNode(def_string, "key");
            node_member_1__003A_ = new CharNode(CharClass.FromUndelimitedCharClassText(":"), ":");
            node_member_2_value = new DefRefNode(def_value, "value");
            def_member.Nodes.Add(node_member_0_key);
            def_member.Nodes.Add(node_member_1__003A_);
            def_member.Nodes.Add(node_member_2_value);
            def_member.StartNodes.Add(node_member_0_key);
            def_member.EndNodes.Add(node_member_2_value);
            node_member_0_key.NextNodes.Add(node_member_1__003A_);
            node_member_1__003A_.NextNodes.Add(node_member_2_value);

            node_value_0_false = new CharNode(CharClass.FromUndelimitedCharClassText("f"), "false");
            node_value_1_false = new CharNode(CharClass.FromUndelimitedCharClassText("a"), "false");
            node_value_2_false = new CharNode(CharClass.FromUndelimitedCharClassText("l"), "false");
            node_value_3_false = new CharNode(CharClass.FromUndelimitedCharClassText("s"), "false");
            node_value_4_false = new CharNode(CharClass.FromUndelimitedCharClassText("e"), "false");
            node_value_5_null = new CharNode(CharClass.FromUndelimitedCharClassText("n"), "null");
            node_value_6_null = new CharNode(CharClass.FromUndelimitedCharClassText("u"), "null");
            node_value_7_null = new CharNode(CharClass.FromUndelimitedCharClassText("l"), "null");
            node_value_8_null = new CharNode(CharClass.FromUndelimitedCharClassText("l"), "null");
            node_value_9_true = new CharNode(CharClass.FromUndelimitedCharClassText("t"), "true");
            node_value_10_true = new CharNode(CharClass.FromUndelimitedCharClassText("r"), "true");
            node_value_11_true = new CharNode(CharClass.FromUndelimitedCharClassText("u"), "true");
            node_value_12_true = new CharNode(CharClass.FromUndelimitedCharClassText("e"), "true");
            node_value_13_object = new DefRefNode(def_object, "object");
            node_value_14_array = new DefRefNode(def_array, "array");
            node_value_15_number = new DefRefNode(def_number, "number");
            node_value_16_string = new DefRefNode(def_string, "string");
            def_value.Nodes.Add(node_value_0_false);
            def_value.Nodes.Add(node_value_1_false);
            def_value.Nodes.Add(node_value_2_false);
            def_value.Nodes.Add(node_value_3_false);
            def_value.Nodes.Add(node_value_4_false);
            def_value.Nodes.Add(node_value_5_null);
            def_value.Nodes.Add(node_value_6_null);
            def_value.Nodes.Add(node_value_7_null);
            def_value.Nodes.Add(node_value_8_null);
            def_value.Nodes.Add(node_value_9_true);
            def_value.Nodes.Add(node_value_10_true);
            def_value.Nodes.Add(node_value_11_true);
            def_value.Nodes.Add(node_value_12_true);
            def_value.Nodes.Add(node_value_13_object);
            def_value.Nodes.Add(node_value_14_array);
            def_value.Nodes.Add(node_value_15_number);
            def_value.Nodes.Add(node_value_16_string);
            def_value.StartNodes.Add(node_value_0_false);
            def_value.StartNodes.Add(node_value_5_null);
            def_value.StartNodes.Add(node_value_9_true);
            def_value.StartNodes.Add(node_value_13_object);
            def_value.StartNodes.Add(node_value_14_array);
            def_value.StartNodes.Add(node_value_15_number);
            def_value.StartNodes.Add(node_value_16_string);
            def_value.EndNodes.Add(node_value_4_false);
            def_value.EndNodes.Add(node_value_8_null);
            def_value.EndNodes.Add(node_value_12_true);
            def_value.EndNodes.Add(node_value_13_object);
            def_value.EndNodes.Add(node_value_14_array);
            def_value.EndNodes.Add(node_value_15_number);
            def_value.EndNodes.Add(node_value_16_string);
            node_value_0_false.NextNodes.Add(node_value_1_false);
            node_value_1_false.NextNodes.Add(node_value_2_false);
            node_value_2_false.NextNodes.Add(node_value_3_false);
            node_value_3_false.NextNodes.Add(node_value_4_false);
            node_value_5_null.NextNodes.Add(node_value_6_null);
            node_value_6_null.NextNodes.Add(node_value_7_null);
            node_value_7_null.NextNodes.Add(node_value_8_null);
            node_value_9_true.NextNodes.Add(node_value_10_true);
            node_value_10_true.NextNodes.Add(node_value_11_true);
            node_value_11_true.NextNodes.Add(node_value_12_true);

            node_number_0__002D_ = new CharNode(CharClass.FromUndelimitedCharClassText("-"), "-");
            node_number_1_0 = new CharNode(CharClass.FromUndelimitedCharClassText("0"), "0");
            node_number_2_123456789 = new CharNode(CharClass.FromUndelimitedCharClassText("123456789"), "123456789");
            node_number_3__005C_d = new CharNode(CharClass.FromUndelimitedCharClassText("\\d"), "\\d");
            node_number_4__002E_ = new CharNode(CharClass.FromUndelimitedCharClassText("."), ".");
            node_number_5__005C_d = new CharNode(CharClass.FromUndelimitedCharClassText("\\d"), "\\d");
            node_number_6_Ee = new CharNode(CharClass.FromUndelimitedCharClassText("Ee"), "Ee");
            node_number_7__002B__002D_ = new CharNode(CharClass.FromUndelimitedCharClassText("+-"), "+-");
            node_number_8__005C_d = new CharNode(CharClass.FromUndelimitedCharClassText("\\d"), "\\d");
            def_number.Nodes.Add(node_number_0__002D_);
            def_number.Nodes.Add(node_number_1_0);
            def_number.Nodes.Add(node_number_2_123456789);
            def_number.Nodes.Add(node_number_3__005C_d);
            def_number.Nodes.Add(node_number_4__002E_);
            def_number.Nodes.Add(node_number_5__005C_d);
            def_number.Nodes.Add(node_number_6_Ee);
            def_number.Nodes.Add(node_number_7__002B__002D_);
            def_number.Nodes.Add(node_number_8__005C_d);
            def_number.StartNodes.Add(node_number_0__002D_);
            def_number.StartNodes.Add(node_number_1_0);
            def_number.StartNodes.Add(node_number_2_123456789);
            def_number.EndNodes.Add(node_number_8__005C_d);
            def_number.EndNodes.Add(node_number_5__005C_d);
            def_number.EndNodes.Add(node_number_1_0);
            def_number.EndNodes.Add(node_number_3__005C_d);
            def_number.EndNodes.Add(node_number_2_123456789);
            node_number_0__002D_.NextNodes.Add(node_number_1_0);
            node_number_0__002D_.NextNodes.Add(node_number_2_123456789);
            node_number_1_0.NextNodes.Add(node_number_4__002E_);
            node_number_1_0.NextNodes.Add(node_number_6_Ee);
            node_number_2_123456789.NextNodes.Add(node_number_3__005C_d);
            node_number_2_123456789.NextNodes.Add(node_number_4__002E_);
            node_number_2_123456789.NextNodes.Add(node_number_6_Ee);
            node_number_3__005C_d.NextNodes.Add(node_number_3__005C_d);
            node_number_3__005C_d.NextNodes.Add(node_number_4__002E_);
            node_number_3__005C_d.NextNodes.Add(node_number_6_Ee);
            node_number_4__002E_.NextNodes.Add(node_number_5__005C_d);
            node_number_5__005C_d.NextNodes.Add(node_number_5__005C_d);
            node_number_5__005C_d.NextNodes.Add(node_number_6_Ee);
            node_number_6_Ee.NextNodes.Add(node_number_7__002B__002D_);
            node_number_6_Ee.NextNodes.Add(node_number_8__005C_d);
            node_number_7__002B__002D_.NextNodes.Add(node_number_8__005C_d);
            node_number_8__005C_d.NextNodes.Add(node_number_8__005C_d);

            node_string_0__0022_ = new CharNode(CharClass.FromUndelimitedCharClassText("\""), "\"");
            node_string_1_char = new DefRefNode(def_char, "char");
            node_string_2__0022_ = new CharNode(CharClass.FromUndelimitedCharClassText("\""), "\"");
            def_string.Nodes.Add(node_string_0__0022_);
            def_string.Nodes.Add(node_string_1_char);
            def_string.Nodes.Add(node_string_2__0022_);
            def_string.StartNodes.Add(node_string_0__0022_);
            def_string.EndNodes.Add(node_string_2__0022_);
            node_string_0__0022_.NextNodes.Add(node_string_1_char);
            node_string_0__0022_.NextNodes.Add(node_string_2__0022_);
            node_string_1_char.NextNodes.Add(node_string_1_char);
            node_string_1_char.NextNodes.Add(node_string_2__0022_);

            node_char_0_unescaped = new DefRefNode(def_unescaped, "unescaped");
            node_char_1__005C_ = new CharNode(CharClass.FromUndelimitedCharClassText("\\\\"), "\\");
            node_char_2__0022__002F__005C__005C_bfnrt = new CharNode(CharClass.FromUndelimitedCharClassText("\"/\\\\bfnrt"), "\"/\\\\bfnrt");
            node_char_3_u = new CharNode(CharClass.FromUndelimitedCharClassText("u"), "u");
            node_char_4__005C_dabcdef = new CharNode(CharClass.FromUndelimitedCharClassText("\\dabcdef"), "\\dabcdef");
            node_char_5__005C_dabcdef = new CharNode(CharClass.FromUndelimitedCharClassText("\\dabcdef"), "\\dabcdef");
            node_char_6__005C_dabcdef = new CharNode(CharClass.FromUndelimitedCharClassText("\\dabcdef"), "\\dabcdef");
            node_char_7__005C_dabcdef = new CharNode(CharClass.FromUndelimitedCharClassText("\\dabcdef"), "\\dabcdef");
            def_char.Nodes.Add(node_char_0_unescaped);
            def_char.Nodes.Add(node_char_1__005C_);
            def_char.Nodes.Add(node_char_2__0022__002F__005C__005C_bfnrt);
            def_char.Nodes.Add(node_char_3_u);
            def_char.Nodes.Add(node_char_4__005C_dabcdef);
            def_char.Nodes.Add(node_char_5__005C_dabcdef);
            def_char.Nodes.Add(node_char_6__005C_dabcdef);
            def_char.Nodes.Add(node_char_7__005C_dabcdef);
            def_char.StartNodes.Add(node_char_0_unescaped);
            def_char.StartNodes.Add(node_char_1__005C_);
            def_char.EndNodes.Add(node_char_0_unescaped);
            def_char.EndNodes.Add(node_char_2__0022__002F__005C__005C_bfnrt);
            def_char.EndNodes.Add(node_char_7__005C_dabcdef);
            node_char_1__005C_.NextNodes.Add(node_char_2__0022__002F__005C__005C_bfnrt);
            node_char_1__005C_.NextNodes.Add(node_char_3_u);
            node_char_3_u.NextNodes.Add(node_char_4__005C_dabcdef);
            node_char_4__005C_dabcdef.NextNodes.Add(node_char_5__005C_dabcdef);
            node_char_5__005C_dabcdef.NextNodes.Add(node_char_6__005C_dabcdef);
            node_char_6__005C_dabcdef.NextNodes.Add(node_char_7__005C_dabcdef);

            node_unescaped_0__005C_l_005C_d_0020__0021__0023__0024__0025__0026__0027__0028__0029__002A__002B__002C__002D__002E__002F__003A__003B__003C__003D__003E__003F__0040__005C__005B__005C__005D__005E__005F__0060__007B__007C__007D__007E_ = new CharNode(CharClass.FromUndelimitedCharClassText("\\l\\d !#$%&'()*+,-./:;<=>?@\\[\\]^_`{|}~"), "\\l\\d !#$%&'()*+,-./:;<=>?@\\[\\]^_`{|}~");
            def_unescaped.Nodes.Add(node_unescaped_0__005C_l_005C_d_0020__0021__0023__0024__0025__0026__0027__0028__0029__002A__002B__002C__002D__002E__002F__003A__003B__003C__003D__003E__003F__0040__005C__005B__005C__005D__005E__005F__0060__007B__007C__007D__007E_);
            def_unescaped.StartNodes.Add(node_unescaped_0__005C_l_005C_d_0020__0021__0023__0024__0025__0026__0027__0028__0029__002A__002B__002C__002D__002E__002F__003A__003B__003C__003D__003E__003F__0040__005C__005B__005C__005D__005E__005F__0060__007B__007C__007D__007E_);
            def_unescaped.EndNodes.Add(node_unescaped_0__005C_l_005C_d_0020__0021__0023__0024__0025__0026__0027__0028__0029__002A__002B__002C__002D__002E__002F__003A__003B__003C__003D__003E__003F__0040__005C__005B__005C__005D__005E__005F__0060__007B__007C__007D__007E_);

            node_array_0__005B_ = new CharNode(CharClass.FromUndelimitedCharClassText("\\["), "[");
            node_array_1_value = new DefRefNode(def_value, "value");
            node_array_2__002C_ = new CharNode(CharClass.FromUndelimitedCharClassText(","), ",");
            node_array_3_value = new DefRefNode(def_value, "value");
            node_array_4__005D_ = new CharNode(CharClass.FromUndelimitedCharClassText("\\]"), "]");
            def_array.Nodes.Add(node_array_0__005B_);
            def_array.Nodes.Add(node_array_1_value);
            def_array.Nodes.Add(node_array_2__002C_);
            def_array.Nodes.Add(node_array_3_value);
            def_array.Nodes.Add(node_array_4__005D_);
            def_array.StartNodes.Add(node_array_0__005B_);
            def_array.EndNodes.Add(node_array_4__005D_);
            node_array_0__005B_.NextNodes.Add(node_array_1_value);
            node_array_0__005B_.NextNodes.Add(node_array_4__005D_);
            node_array_1_value.NextNodes.Add(node_array_2__002C_);
            node_array_1_value.NextNodes.Add(node_array_4__005D_);
            node_array_2__002C_.NextNodes.Add(node_array_3_value);
            node_array_3_value.NextNodes.Add(node_array_2__002C_);
            node_array_3_value.NextNodes.Add(node_array_4__005D_);

        }
    }
}

