using System;

namespace MetaphysicsIndustries.Giza
{
    public class LispGrammar : Grammar
    {
        public Definition def_0_expr = new Definition("expr");
        public Definition def_1_s_expr = new Definition("s-expr");
        public Definition def_2_number = new Definition("number");
        public Definition def_3_string = new Definition("string");
        public Definition def_4_unicodechar = new Definition("unicodechar");
        public Definition def_5_identifier = new Definition("identifier");
        public Definition def_6__implicit_literal__ = new Definition("$implicit literal '");
        public Definition def_7__implicit_literal__ = new Definition("$implicit literal (");
        public Definition def_8__implicit_literal__ = new Definition("$implicit literal )");

        public DefRefNode node_expr_0__0027_;
        public DefRefNode node_expr_1_s_002D_expr;
        public DefRefNode node_expr_2_number;
        public DefRefNode node_expr_3_string;
        public DefRefNode node_expr_4_identifier;
        public DefRefNode node_s_expr_0__0028_;
        public DefRefNode node_s_expr_1_expr;
        public DefRefNode node_s_expr_2__0029_;
        public CharNode node_number_0_0b;
        public CharNode node_number_1_0b;
        public CharNode node_number_2_01;
        public CharNode node_number_3_0o;
        public CharNode node_number_4_0o;
        public CharNode node_number_5_01234567;
        public CharNode node_number_6_0x;
        public CharNode node_number_7_0x;
        public CharNode node_number_8__005C_dabcdef;
        public CharNode node_number_9__005C_d;
        public CharNode node_number_10__002E_;
        public CharNode node_number_11__005C_d;
        public CharNode node_number_12_eE;
        public CharNode node_number_13__002B__002D_;
        public CharNode node_number_14__005C_d;
        public CharNode node_string_0__0022_;
        public CharNode node_string_1__005E__005C__005C__0022_;
        public CharNode node_string_2__005C_;
        public CharNode node_string_3_wldsrnt_005C__005C__0022_;
        public DefRefNode node_string_4_unicodechar;
        public CharNode node_string_5__0022_;
        public CharNode node_unicodechar_0__005C_x;
        public CharNode node_unicodechar_1__005C_x;
        public CharNode node_unicodechar_2__005C_dabcdef;
        public CharNode node_unicodechar_3__005C_dabcdef;
        public CharNode node_unicodechar_4__005C_dabcdef;
        public CharNode node_unicodechar_5__005C_dabcdef;
        public CharNode node_identifier_0__005C_l;
        public CharNode node__implicit_literal___0_;
        public CharNode node__implicit_literal___0_;
        public CharNode node__implicit_literal___0_;

        public LispGrammar()
        {
            Definitions.Add(def_0_expr);
            Definitions.Add(def_1_s_expr);
            Definitions.Add(def_2_number);
            Definitions.Add(def_3_string);
            Definitions.Add(def_4_unicodechar);
            Definitions.Add(def_5_identifier);
            Definitions.Add(def_6__implicit_literal__);
            Definitions.Add(def_7__implicit_literal__);
            Definitions.Add(def_8__implicit_literal__);

            node_expr_0__0027_ = new DefRefNode(def_6__implicit_literal__, "'");
            node_expr_1_s_002D_expr = new DefRefNode(def_1_s_expr, "s-expr");
            node_expr_2_number = new DefRefNode(def_2_number, "number");
            node_expr_3_string = new DefRefNode(def_3_string, "string");
            node_expr_4_identifier = new DefRefNode(def_5_identifier, "identifier");
            def_0_expr.Nodes.Add(node_expr_0__0027_);
            def_0_expr.Nodes.Add(node_expr_1_s_002D_expr);
            def_0_expr.Nodes.Add(node_expr_2_number);
            def_0_expr.Nodes.Add(node_expr_3_string);
            def_0_expr.Nodes.Add(node_expr_4_identifier);
            def_0_expr.StartNodes.Add(node_expr_0__0027_);
            def_0_expr.StartNodes.Add(node_expr_1_s_002D_expr);
            def_0_expr.StartNodes.Add(node_expr_2_number);
            def_0_expr.StartNodes.Add(node_expr_3_string);
            def_0_expr.StartNodes.Add(node_expr_4_identifier);
            def_0_expr.EndNodes.Add(node_expr_1_s_002D_expr);
            def_0_expr.EndNodes.Add(node_expr_2_number);
            def_0_expr.EndNodes.Add(node_expr_3_string);
            def_0_expr.EndNodes.Add(node_expr_4_identifier);
            node_expr_0__0027_.NextNodes.Add(node_expr_1_s_002D_expr);
            node_expr_0__0027_.NextNodes.Add(node_expr_2_number);
            node_expr_0__0027_.NextNodes.Add(node_expr_3_string);
            node_expr_0__0027_.NextNodes.Add(node_expr_4_identifier);

            node_s_expr_0__0028_ = new DefRefNode(def_7__implicit_literal__, "(");
            node_s_expr_1_expr = new DefRefNode(def_0_expr, "expr");
            node_s_expr_2__0029_ = new DefRefNode(def_8__implicit_literal__, ")");
            def_1_s_expr.Nodes.Add(node_s_expr_0__0028_);
            def_1_s_expr.Nodes.Add(node_s_expr_1_expr);
            def_1_s_expr.Nodes.Add(node_s_expr_2__0029_);
            def_1_s_expr.StartNodes.Add(node_s_expr_0__0028_);
            def_1_s_expr.EndNodes.Add(node_s_expr_2__0029_);
            node_s_expr_0__0028_.NextNodes.Add(node_s_expr_1_expr);
            node_s_expr_0__0028_.NextNodes.Add(node_s_expr_2__0029_);
            node_s_expr_1_expr.NextNodes.Add(node_s_expr_1_expr);
            node_s_expr_1_expr.NextNodes.Add(node_s_expr_2__0029_);

            def_2_number.Directives.Add(DefinitionDirective.Token);
            def_2_number.Directives.Add(DefinitionDirective.Atomic);
            node_number_0_0b = new CharNode(CharClass.FromUndelimitedCharClassText("0"), "0b");
            node_number_1_0b = new CharNode(CharClass.FromUndelimitedCharClassText("b"), "0b");
            node_number_2_01 = new CharNode(CharClass.FromUndelimitedCharClassText("01"), "01");
            node_number_3_0o = new CharNode(CharClass.FromUndelimitedCharClassText("0"), "0o");
            node_number_4_0o = new CharNode(CharClass.FromUndelimitedCharClassText("o"), "0o");
            node_number_5_01234567 = new CharNode(CharClass.FromUndelimitedCharClassText("01234567"), "01234567");
            node_number_6_0x = new CharNode(CharClass.FromUndelimitedCharClassText("0"), "0x");
            node_number_7_0x = new CharNode(CharClass.FromUndelimitedCharClassText("x"), "0x");
            node_number_8__005C_dabcdef = new CharNode(CharClass.FromUndelimitedCharClassText("\\dabcdef"), "\\dabcdef");
            node_number_9__005C_d = new CharNode(CharClass.FromUndelimitedCharClassText("\\d"), "\\d");
            node_number_10__002E_ = new CharNode(CharClass.FromUndelimitedCharClassText("."), ".");
            node_number_11__005C_d = new CharNode(CharClass.FromUndelimitedCharClassText("\\d"), "\\d");
            node_number_12_eE = new CharNode(CharClass.FromUndelimitedCharClassText("eE"), "eE");
            node_number_13__002B__002D_ = new CharNode(CharClass.FromUndelimitedCharClassText("+-"), "+-");
            node_number_14__005C_d = new CharNode(CharClass.FromUndelimitedCharClassText("\\d"), "\\d");
            def_2_number.Nodes.Add(node_number_0_0b);
            def_2_number.Nodes.Add(node_number_1_0b);
            def_2_number.Nodes.Add(node_number_2_01);
            def_2_number.Nodes.Add(node_number_3_0o);
            def_2_number.Nodes.Add(node_number_4_0o);
            def_2_number.Nodes.Add(node_number_5_01234567);
            def_2_number.Nodes.Add(node_number_6_0x);
            def_2_number.Nodes.Add(node_number_7_0x);
            def_2_number.Nodes.Add(node_number_8__005C_dabcdef);
            def_2_number.Nodes.Add(node_number_9__005C_d);
            def_2_number.Nodes.Add(node_number_10__002E_);
            def_2_number.Nodes.Add(node_number_11__005C_d);
            def_2_number.Nodes.Add(node_number_12_eE);
            def_2_number.Nodes.Add(node_number_13__002B__002D_);
            def_2_number.Nodes.Add(node_number_14__005C_d);
            def_2_number.StartNodes.Add(node_number_0_0b);
            def_2_number.StartNodes.Add(node_number_3_0o);
            def_2_number.StartNodes.Add(node_number_6_0x);
            def_2_number.StartNodes.Add(node_number_9__005C_d);
            def_2_number.EndNodes.Add(node_number_2_01);
            def_2_number.EndNodes.Add(node_number_5_01234567);
            def_2_number.EndNodes.Add(node_number_8__005C_dabcdef);
            def_2_number.EndNodes.Add(node_number_14__005C_d);
            def_2_number.EndNodes.Add(node_number_11__005C_d);
            def_2_number.EndNodes.Add(node_number_9__005C_d);
            node_number_0_0b.NextNodes.Add(node_number_1_0b);
            node_number_1_0b.NextNodes.Add(node_number_2_01);
            node_number_2_01.NextNodes.Add(node_number_2_01);
            node_number_3_0o.NextNodes.Add(node_number_4_0o);
            node_number_4_0o.NextNodes.Add(node_number_5_01234567);
            node_number_5_01234567.NextNodes.Add(node_number_5_01234567);
            node_number_6_0x.NextNodes.Add(node_number_7_0x);
            node_number_7_0x.NextNodes.Add(node_number_8__005C_dabcdef);
            node_number_8__005C_dabcdef.NextNodes.Add(node_number_8__005C_dabcdef);
            node_number_9__005C_d.NextNodes.Add(node_number_9__005C_d);
            node_number_9__005C_d.NextNodes.Add(node_number_10__002E_);
            node_number_9__005C_d.NextNodes.Add(node_number_12_eE);
            node_number_10__002E_.NextNodes.Add(node_number_11__005C_d);
            node_number_11__005C_d.NextNodes.Add(node_number_11__005C_d);
            node_number_11__005C_d.NextNodes.Add(node_number_12_eE);
            node_number_12_eE.NextNodes.Add(node_number_13__002B__002D_);
            node_number_12_eE.NextNodes.Add(node_number_14__005C_d);
            node_number_13__002B__002D_.NextNodes.Add(node_number_14__005C_d);
            node_number_14__005C_d.NextNodes.Add(node_number_14__005C_d);

            def_3_string.Directives.Add(DefinitionDirective.Token);
            def_3_string.Directives.Add(DefinitionDirective.IncludeWhitespace);
            def_3_string.Directives.Add(DefinitionDirective.Atomic);
            node_string_0__0022_ = new CharNode(CharClass.FromUndelimitedCharClassText("\\""), "\\"");
            node_string_1__005E__005C__005C__0022_ = new CharNode(CharClass.FromUndelimitedCharClassText("^\\\\\\""), "^\\\\\\"");
            node_string_2__005C_ = new CharNode(CharClass.FromUndelimitedCharClassText("\\\\"), "\\");
            node_string_3_wldsrnt_005C__005C__0022_ = new CharNode(CharClass.FromUndelimitedCharClassText("wldsrnt\\\\\\""), "wldsrnt\\\\\\"");
            node_string_4_unicodechar = new DefRefNode(def_4_unicodechar, "unicodechar");
            node_string_5__0022_ = new CharNode(CharClass.FromUndelimitedCharClassText("\\""), "\\"");
            def_3_string.Nodes.Add(node_string_0__0022_);
            def_3_string.Nodes.Add(node_string_1__005E__005C__005C__0022_);
            def_3_string.Nodes.Add(node_string_2__005C_);
            def_3_string.Nodes.Add(node_string_3_wldsrnt_005C__005C__0022_);
            def_3_string.Nodes.Add(node_string_4_unicodechar);
            def_3_string.Nodes.Add(node_string_5__0022_);
            def_3_string.StartNodes.Add(node_string_0__0022_);
            def_3_string.EndNodes.Add(node_string_5__0022_);
            node_string_0__0022_.NextNodes.Add(node_string_1__005E__005C__005C__0022_);
            node_string_0__0022_.NextNodes.Add(node_string_2__005C_);
            node_string_0__0022_.NextNodes.Add(node_string_4_unicodechar);
            node_string_1__005E__005C__005C__0022_.NextNodes.Add(node_string_1__005E__005C__005C__0022_);
            node_string_1__005E__005C__005C__0022_.NextNodes.Add(node_string_2__005C_);
            node_string_1__005E__005C__005C__0022_.NextNodes.Add(node_string_4_unicodechar);
            node_string_1__005E__005C__005C__0022_.NextNodes.Add(node_string_5__0022_);
            node_string_2__005C_.NextNodes.Add(node_string_3_wldsrnt_005C__005C__0022_);
            node_string_3_wldsrnt_005C__005C__0022_.NextNodes.Add(node_string_1__005E__005C__005C__0022_);
            node_string_3_wldsrnt_005C__005C__0022_.NextNodes.Add(node_string_2__005C_);
            node_string_3_wldsrnt_005C__005C__0022_.NextNodes.Add(node_string_4_unicodechar);
            node_string_3_wldsrnt_005C__005C__0022_.NextNodes.Add(node_string_5__0022_);
            node_string_4_unicodechar.NextNodes.Add(node_string_1__005E__005C__005C__0022_);
            node_string_4_unicodechar.NextNodes.Add(node_string_2__005C_);
            node_string_4_unicodechar.NextNodes.Add(node_string_4_unicodechar);
            node_string_4_unicodechar.NextNodes.Add(node_string_5__0022_);

            def_4_unicodechar.Directives.Add(DefinitionDirective.Subtoken);
            def_4_unicodechar.Directives.Add(DefinitionDirective.IgnoreCase);
            def_4_unicodechar.Directives.Add(DefinitionDirective.Atomic);
            node_unicodechar_0__005C_x = new CharNode(CharClass.FromUndelimitedCharClassText("\\\\"), "\\x");
            node_unicodechar_1__005C_x = new CharNode(CharClass.FromUndelimitedCharClassText("x"), "\\x");
            node_unicodechar_2__005C_dabcdef = new CharNode(CharClass.FromUndelimitedCharClassText("\\dabcdef"), "\\dabcdef");
            node_unicodechar_3__005C_dabcdef = new CharNode(CharClass.FromUndelimitedCharClassText("\\dabcdef"), "\\dabcdef");
            node_unicodechar_4__005C_dabcdef = new CharNode(CharClass.FromUndelimitedCharClassText("\\dabcdef"), "\\dabcdef");
            node_unicodechar_5__005C_dabcdef = new CharNode(CharClass.FromUndelimitedCharClassText("\\dabcdef"), "\\dabcdef");
            def_4_unicodechar.Nodes.Add(node_unicodechar_0__005C_x);
            def_4_unicodechar.Nodes.Add(node_unicodechar_1__005C_x);
            def_4_unicodechar.Nodes.Add(node_unicodechar_2__005C_dabcdef);
            def_4_unicodechar.Nodes.Add(node_unicodechar_3__005C_dabcdef);
            def_4_unicodechar.Nodes.Add(node_unicodechar_4__005C_dabcdef);
            def_4_unicodechar.Nodes.Add(node_unicodechar_5__005C_dabcdef);
            def_4_unicodechar.StartNodes.Add(node_unicodechar_0__005C_x);
            def_4_unicodechar.EndNodes.Add(node_unicodechar_5__005C_dabcdef);
            node_unicodechar_0__005C_x.NextNodes.Add(node_unicodechar_1__005C_x);
            node_unicodechar_1__005C_x.NextNodes.Add(node_unicodechar_2__005C_dabcdef);
            node_unicodechar_2__005C_dabcdef.NextNodes.Add(node_unicodechar_3__005C_dabcdef);
            node_unicodechar_3__005C_dabcdef.NextNodes.Add(node_unicodechar_4__005C_dabcdef);
            node_unicodechar_4__005C_dabcdef.NextNodes.Add(node_unicodechar_5__005C_dabcdef);

            def_5_identifier.Directives.Add(DefinitionDirective.Token);
            def_5_identifier.Directives.Add(DefinitionDirective.Atomic);
            node_identifier_0__005C_l = new CharNode(CharClass.FromUndelimitedCharClassText("\\l"), "\\l");
            def_5_identifier.Nodes.Add(node_identifier_0__005C_l);
            def_5_identifier.StartNodes.Add(node_identifier_0__005C_l);
            def_5_identifier.EndNodes.Add(node_identifier_0__005C_l);
            node_identifier_0__005C_l.NextNodes.Add(node_identifier_0__005C_l);

            def_6__implicit_literal__.Directives.Add(DefinitionDirective.Token);
            def_6__implicit_literal__.Directives.Add(DefinitionDirective.Atomic);
            node__implicit_literal___0_ = new CharNode(CharClass.FromUndelimitedCharClassText("'"), "");
            def_6__implicit_literal__.Nodes.Add(node__implicit_literal___0_);
            def_6__implicit_literal__.StartNodes.Add(node__implicit_literal___0_);
            def_6__implicit_literal__.EndNodes.Add(node__implicit_literal___0_);

            def_7__implicit_literal__.Directives.Add(DefinitionDirective.Token);
            def_7__implicit_literal__.Directives.Add(DefinitionDirective.Atomic);
            node__implicit_literal___0_ = new CharNode(CharClass.FromUndelimitedCharClassText("("), "");
            def_7__implicit_literal__.Nodes.Add(node__implicit_literal___0_);
            def_7__implicit_literal__.StartNodes.Add(node__implicit_literal___0_);
            def_7__implicit_literal__.EndNodes.Add(node__implicit_literal___0_);

            def_8__implicit_literal__.Directives.Add(DefinitionDirective.Token);
            def_8__implicit_literal__.Directives.Add(DefinitionDirective.Atomic);
            node__implicit_literal___0_ = new CharNode(CharClass.FromUndelimitedCharClassText(")"), "");
            def_8__implicit_literal__.Nodes.Add(node__implicit_literal___0_);
            def_8__implicit_literal__.StartNodes.Add(node__implicit_literal___0_);
            def_8__implicit_literal__.EndNodes.Add(node__implicit_literal___0_);

        }
    }
}

